### PR TITLE
Perf : Save ratings count in notices entities

### PR DESCRIPTION
**Pull request by JalilArfaoui**
For each display of notices list in back-office and every call of the API with notices info or notices list, we are counting the number of ratings for **each type of rating** … No wonder why this was getting slow and consuming up to **1 GB** of memory just to show 20 notices in back-office !

What I did here is to store the count of `badged`, `display`, `unfold`, `clicked`, `liked`, 'disliked` and `dismissed` events directly in `Notice` entities, and update the corresponding count every time a rating is `POST`ed.

Showing the same page now consumes approx 15-20MB of memory (tested with production database) … back to normal.

For now, with the added index, the rating `POST` is quick enough (400 ms), so I left the bus synchronous, but later, it would be possible to make it asynchronous, and event to group updates. 

Note that this breaks a bit the single source of truth, but it also shows the way to CQRS if you think about it :-) …

@MaartenLMEM @Etienne-DisMoi One nice side effect is that you can now sort the notices by ratings in the back-office. (I also changed some table headers to emojis to save some space)

It would be possible to do the same with `relayersCount` if this proves useful.

### CODE REVIEW

**Review by gregoirelacoste — APPROVED** [review]
Nice, big performance gain indeed!
it will now be necessary to implement methods in front to increment these new fields?

**Comment by JalilArfaoui** [comment]
> it will now be necessary to implement methods in front to increment these new fields?

@gregoirelacoste nope, no change on the API side, same fields are filled,

**Comment by JalilArfaoui** [comment]
@MaartenLMEM @Etienne-DisMoi It’s merged and available on https://staging-notices.bulles.fr … Can you validate functionnally ?

**Comment by JalilArfaoui** [comment]
This is now in production.

**Pull request merged**
