### PR TITLE
API v4 with JWT Authentication

### PR DESCRIPTION
**Pull request by Goutte**
Initial rushes of an implementation of the API using ApiPlatform and Json Web Tokens (JWT).

Of note: 

- Requires a database migration
- Users are now linked to Contributors (users have hats / contributors have impersonators)
- Publishing a Notice in the name of a Contributor is only allowed if the authenticated User is allowed to impersonate the Contributor.
- Doc and sandbox at `/api/v4/docs.html`.

### CODE REVIEW

**Comment by lutangar** [comment]
Rebase and CS fix plz!

```
docker-compose exec php vendor/bin/php-cs-fixer fix
docker-compose exec php vendor/bin/phpstan analyse
```

**Comment by Goutte** [comment]
The linter removes a use statement that annotations need.  (`NoticeVoter`, in `Notice`)
It also removes spaces around the `!` in conditions, which I strongly disagree with, for accessibility reasons.

**Comment by lutangar** [comment]
> The linter removes a use statement that annotations need. (NoticeVoter, in Notice)

It shouldn't, let's fix that.

> It also removes spaces around the ! in conditions, which I strongly disagree with, for accessibility reasons.

Alright let's change that too.

**Comment by Goutte** [comment]
I fixed the spaces around the NOT operator.

The first (unused `use` statements), I'm not sure how to fix !

**Comment by Goutte** [comment]
PAIN

**Comment by Goutte** [comment]
Now this is garbage : see #374

**Pull request closed without merging**
