### PR TITLE
feat(matching): introduce product matching engine

### LINKED ISSUE #448: Revamping the Backend UI for matching-context : create product targeted fields
## Stakes
Transitioning from regex and xpath to nocode

## Context
Today, the matching context has the following fields 
Capture d’écran 2021-09-13 à 13 01 06

The fields Regex target the url whereas xpath target the Document Object Model (DOM). Those two fields, need a special expertise to be used, hence not user friendly

## Wished evolution
Web pages often have a similar structure : 

### Product
- ~Title~ Name
- Category
- Description
- Price

###  Offer
- Location

The previous parts should be targetable directly from the backend.

### For Title, Category, and Description the possibility would be to have the following options logical connectors 
AND OR EXCEPT
i.e. 
(term1 and term2) or term3 except term4

### For Price, the following possibility should be to have the following mathematical functions
lower than <, greater than, lower than or equal to <=, greater than or equal to >=

Ie.
lower than or equal to <= number 1 and greater than > number 2

### For the last part location, a more intuitive way would be to select cities or regions directly from a dropdown list or a map.

### PR DESCRIPTION
**Pull request by lutangar**
Uses part of the https://schema.org vocabulary.
Make use of the api platform schema generator to bootstrap entities.

> resolves #448

This still miss a few tests and CS and stan analysis fixes but the concept is already reviewable @JalilArfaoui 

Screenshot from 2021-09-22 18-14-38

### CODE REVIEW

**Comment by MaartenLMEM** [comment]
@lutangar we need all fields that are mentionned in the issue.
In the scrernshot I do not see those :
- `Product name And`
- `Product name Or`  
- `Product name Excluded`  

Same for other categorie we need what we asked. 
Otherwise contributors will have to fullfill several time same fields and add comment saying this is ok but only if we exclude this term etc.

**Review by JalilArfaoui — APPROVED** [review]

**Comment by JalilArfaoui** [comment]
@lutangar @MaartenLMEM I’m merging this so that we can start filling the field …

**Comment by JalilArfaoui** [comment]
@MaartenLMEM can you approve this in staging and confirm deployment to production ?

**Comment by JalilArfaoui** [comment]
Maybe we can have a look at this together @prk-dismoi

**Comment by JalilArfaoui** [comment]
@MaartenLMEM this is already merged and in staging...

Either it's good enough to be pushed, either we rollback or amend the changes...

**Comment by MaartenLMEM** [comment]
ok no problem we can keep it

**Pull request merged**
