### PR TITLE
add install docker on your machine step

### PR DESCRIPTION
**Pull request by felix-lambert**

### CODE REVIEW

**Review by JalilArfaoui — APPROVED** [review]
LGTM

**Comment by achauve** [comment]
When possible I think it would be great to split these kinds of commits in two new commits to make it quicker to review, and later easier to go through history when bug hunting:
- one with minor refactoring (blank lines, whitespaces, reformatting, etc.)
- one with actual content change (here the addition of docker instructions)

**Comment by lutangar** [comment]
@felix-lambert as per @achauve suggestion, could you include only the actual change in this PR?

If you have some preferred conventions for the markdown, let's create an issue for that and find a way to enforce the convention in the code.

**Review by lutangar — APPROVED** [review]

**Review by lutangar — APPROVED** [review]
:+1:

**Pull request merged**
