### PR TITLE
Migration to Symfony 4 and EasyAdmin 2

### PR DESCRIPTION
**Pull request by JalilArfaoui**

### CODE REVIEW

**Review by lutangar — CHANGES_REQUESTED** [review]
Maybe I didn't merge the PRs in the right order but there are still conflicts left to be resovled.
Also the history seems to have unnecessary commits, I'm not asking for a full refactoring here, just an extra check (saw the commit for the "removing relayer" tests on this branch for example)

**Comment by JalilArfaoui** [comment]
Yes, this is due to the last merged PR s … I’m gonna fix the conficts tomorrow morning

**Comment by JalilArfaoui** [comment]
@lutangar I’ve merged `master` into `migrate/symfony4` and resolved conficts … Everything seems to work and `make test-no-deprecation` is clean

**Comment by lutangar** [comment]
When running `docker-compose up` the PHP container fails to start :
```
kraft-backend_php | Fatal Error: composer.lock was created for PHP version 7.3 or higher but the current PHP version is 7.2.12.
```
> https://stackoverflow.com/questions/59141344/fatal-error-composer-lock-was-created-for-php-version-7-4-or-higher-but-the-cur/59452859#59452859

**Comment by lutangar** [comment]
When running the tests I'm seeing the deprecations warning :
```
Remaining direct deprecation notices (58)
```
Are we staying with this for now?

**Comment by JalilArfaoui** [comment]
> 
> 
> When running the tests I'm seeing the deprecations warning :
> 
> ```
> Remaining direct deprecation notices (58)
> ```
> 
> Are we staying with this for now?

Yes, we will deal with them later

**Comment by JalilArfaoui** [comment]
> 
> 
> When running `docker-compose up` the PHP container fails to start :
> 
> ```
> kraft-backend_php | Fatal Error: composer.lock was created for PHP version 7.3 or higher but the current PHP version is 7.2.12.
> ```
> 
> > https://stackoverflow.com/questions/59141344/fatal-error-composer-lock-was-created-for-php-version-7-4-or-higher-but-the-cur/59452859#59452859
> 
> Edit: Forcing re-creation and build seems to fix the issue :
> 
> ```
> docker-compose up --force-recreate --build 
> ```

Yes, Symfony 4 needs PHP 7.3 if I remember correctly

**Comment by JalilArfaoui** [comment]
`docker-compose up --build --remove-orphans` should work too

**Comment by JalilArfaoui** [comment]
@lutangar you can use `make test-no-deprecation`  to avoid deprecation messages

**Comment by JalilArfaoui** [comment]
@lutangar I’ve rebased and clean some commits 🎉 ;-)

**Review by lutangar — APPROVED** [review]

**Pull request merged**
