### PR TITLE
chore(relayer): Add tests add/remove a relayer

### PR DESCRIPTION
**Pull request by lutangar**
@JalilArfaoui I added tests, but even the test which add a relayer is failing and shouldn't.
Are these tests flawed?

Anyway, I tried to solving the issue preventing the deletion of a relayer but couldn't get it to work properly...
Could you have a look?

As a shortcut to run the tests you may use:
```
make
make test
```

> https://trello.com/c/jPINYfEW/646-impossible-de-supprimer-des-relayeurs

### CODE REVIEW

**Comment by JalilArfaoui** [comment]
I’m going to have a look

**Comment by JalilArfaoui** [comment]
@lutangar I think the failing test has something to do with the way we reference Doctrine's entity manager. I had a similar issue when upgrading Symfony in #277 

In fact, I’ve just added your 2 test cases in the #277 branch and they’re working as-is

**Comment by JalilArfaoui** [comment]
I keep working on making them pass here …

**Comment by JalilArfaoui** [comment]
@lutangar tests fixed and passing … but I’m not sure that this PR fixes the issue we had yet

**Comment by JalilArfaoui** [comment]
(I confirm it does not)

**Comment by JalilArfaoui** [comment]
The issue may be due to https://stackoverflow.com/questions/27771909/symfony-does-not-remove-entity-from-collection …

**Comment by lutangar** [comment]
@JalilArfaoui maybe I didn't make clear that I didn't fix the issue hehe.

> orphanRemoval

Nice catch!

**Pull request merged**
